name: "Unit tests"
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
  workflow_dispatch:
  schedule:
    # run every week (for --pre release tests)
    - cron: "0 0 * * 0"


jobs:
  test_suite:
    runs-on: [self-hosted, linux, x64, gpu]
    container:
      image: continuumio/miniconda3
      options: --runtime=nvidia --gpus all
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          conda install -y python=3.12
      - name: Install base test code
        run: |
          python -m pip install .[test]
          conda list
      - name: Run tests
        run: |
          python -m pytest
