name: "Unit tests"
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
  workflow_dispatch:
  schedule:
    # run every week (for --pre release tests)
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: [self-hosted, linux, x64, gpu]
    container:
      image: continuumio/miniconda3
      options: --runtime=nvidia --gpus all
    
    steps:
    
      - name: Pull code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          conda install -y python=3.12
          
      - name: Install base test code
        run: |
          python -m pip install .[test]
          conda list
          
      - name: 🧪 Run Tests
        run: pytest --color=yes --cov --cov-report=xml --cov-report=term-missing
        
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: covreport
          path: ./.coverage*
          include-hidden-files: true

  upload_coverage:
    if: always()
    needs: [test]
    uses: pyapp-kit/workflows/.github/workflows/upload-coverage.yml@v2
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
