name: CI

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
  workflow_dispatch:
  schedule:
    # run every week (for --pre release tests)
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ubuntu gpu python-${{ matrix.python-version }}
    runs-on: [self-hosted, linux, x64, gpu]
    container:
      image: continuumio/miniconda3
      options: --runtime=nvidia --gpus all
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
    
    steps:
    
      - name: Pull code
        uses: actions/checkout@v4
        
      - name: Set up conda with python-${{ matrix.python-version }}
        run: |
          conda install -y python=${{ matrix.python-version }}
          
      - name: Install base test code
        run: |
          python -m pip install .[test]
          conda list
          
      - name: Run Tests
        run: |
          COVERAGE_FILE=.coverage.${{ matrix.python-version }} pytest --color=yes --cov --cov-report=xml --cov-report=term-missing
        
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: covreport-${{ matrix.python-version }}
          path: ./.coverage*
          include-hidden-files: true

  upload_coverage:
    if: always()
    needs: [test]
    uses: pyapp-kit/workflows/.github/workflows/upload-coverage.yml@v2
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

